FROM node:16

# アプリケーションディレクトリを作成する
WORKDIR /app

# アプリケーションの依存関係をインストールする
COPY frontend/package*.json ./

RUN npm install
# RUN npm install --only=production

#アプリケーションのソースをバンドルする
COPY ./frontend .

EXPOSE 3000

# CMD [ "npm", "start"]