version: "3"

services:
  api:
    container_name: tflapi
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: "npm start"
    ports:
      - 80:8080
    volumes:
      - ./api:/app
      - /app/node_modules
