FROM node:16

# アプリケーションディレクトリを作成する
WORKDIR /app

# アプリケーションの依存関係をインストールする
COPY api/package*.json ./

RUN npm install
# RUN npm install --only=production

#アプリケーションのソースをバンドルする
COPY ./api .

EXPOSE 8080

# CMD [ "npm", "start"]

