version: "3"

services:
  api:
    container_name: tflapi
    build: 
      context: .
      dockerfile: Dockerfile.api
    command: "npm start"
    ports:
      - 80:8080
    volumes:
      - ./api:/app
      - /app/node_modules
  frontend:
    container_name: tflfront
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: "npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    environment:
      - WATCHPACK_POLLING=true